/**
 * dsh-aidrama — host HTTP route family.
 *
 * This is the SINGLE implementation of every project operation. The browser half
 * and the Agent tools both drive these handlers (the Agent path synthesises a
 * req/res pair in lib/index.js), so a commit or a generation batch can never
 * mean two different things depending on who asked.
 *
 * Contract rules, enforced here rather than by convention:
 *
 *  - EVERY route is LOOPBACK-ONLY. `isLoopbackRequest` mirrors dsh-imagegen
 *    exactly, including the browser same-origin markers, so a hostile page in
 *    the user's own browser cannot reach the local API.
 *  - NO API KEY EVER LEAVES THE HOST. `/config` projects channels through an
 *    explicit allow-list and reports only the boolean `hasKey`; asset URLs carry
 *    a file name and nothing else; every error message is scrubbed before it is
 *    written. A key must not be reconstructible from any response.
 *  - A HANDLED failure answers 200 with `{ ok: false, code, message }`. Non-200
 *    is reserved for the loopback/method guards and the asset 404.
 *  - Request bodies are capped at MAX_JSON_BODY_BYTES; an oversized body is
 *    never buffered in full.
 *
 * Plain ESM, zero dependencies, no build step.
 */

import {
  AIDRAMA_API,
  ASSET_KIND,
  IMAGE_STAGES,
  MAX_JSON_BODY_BYTES,
  ORIGIN,
  PROJECT_SCHEMA_VERSION,
  STAGES,
  STAGE_META,
  STAGE_STATUS,
  TEXT_STAGES,
  VIDEO_PROTOCOL,
  isStageId,
} from './protocol.js'

/**
 * Only these mime types are ever served with their own content-type.
 *
 * An unknown type is served as `application/octet-stream` + `attachment`
 * instead. That keeps an uploaded `.html` / `.svg` from ever being rendered
 * inline by the browser on the loopback origin, which would turn the asset
 * route into a same-origin scripting foothold.
 *
 * @type {Record<string, string>}
 */
const SAFE_INLINE_MIME = {
  'image/png': 'image/png',
  'image/jpeg': 'image/jpeg',
  'image/webp': 'image/webp',
  'image/gif': 'image/gif',
  'image/avif': 'image/avif',
  'image/bmp': 'image/bmp',
  'video/mp4': 'video/mp4',
  'video/webm': 'video/webm',
  'video/quicktime': 'video/quicktime',
  'video/x-m4v': 'video/x-m4v',
}

/** Extension → mime, used when an asset record carries no usable `mime`. */
const MIME_BY_EXT = {
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.webp': 'image/webp',
  '.gif': 'image/gif',
  '.avif': 'image/avif',
  '.bmp': 'image/bmp',
  '.mp4': 'video/mp4',
  '.webm': 'video/webm',
  '.mov': 'video/quicktime',
  '.m4v': 'video/x-m4v',
}

/** Mime → extension, so a stored file's name always matches its bytes. */
const EXT_BY_MIME = {
  'image/png': '.png',
  'image/jpeg': '.jpg',
  'image/webp': '.webp',
  'image/gif': '.gif',
  'image/avif': '.avif',
  'image/bmp': '.bmp',
  'video/mp4': '.mp4',
  'video/webm': '.webm',
  'video/quicktime': '.mov',
  'video/x-m4v': '.m4v',
}

/**
 * Pick a file extension for a media type.
 *
 * The asset route derives its Content-Type from the stored file's extension, so
 * a `.png` name on JPEG bytes is served as `image/png` and refused by strict
 * viewers. Unknown types fall back to `.bin`, which the route treats as a
 * download rather than something to render.
 *
 * @param {string} mime
 * @returns {string} an extension including the dot
 */
function extensionForMime(mime) {
  const key = text(mime).split(';')[0].trim().toLowerCase()
  return EXT_BY_MIME[key] ?? '.bin'
}

/** Every asset kind that carries generated bytes (used for `videoTaskCount`). */
const VIDEO_TASK_TERMINAL = new Set([
  'succeeded',
  'failed',
])

/* ------------------------------------------------------------------ *
 * Small helpers
 * ------------------------------------------------------------------ */

/** Human-readable text from an unknown thrown value. */
function messageOf(error) {
  return error instanceof Error ? error.message : String(error)
}

/** Whether `value` is a non-null, non-array object. */
function isRecord(value) {
  return value !== null && typeof value === 'object' && !Array.isArray(value)
}

/** A trimmed string, or `''`. */
function text(value) {
  if (typeof value === 'string') return value.trim()
  if (typeof value === 'number' && Number.isFinite(value)) return String(value)
  return ''
}

/**
 * Scrub anything credential-shaped out of a string that is about to be
 * returned to a client or written to a log.
 *
 * The sibling modules already scrub their own upstream errors, but this layer
 * is the last one before the wire, so it repeats the pass: a `Bearer …` header,
 * an `api_key=` query fragment or an `sk-…` literal must not survive here even
 * if some future caller forgets.
 *
 * @param {unknown} value
 * @returns {string}
 */
function scrub(value) {
  return String(value ?? '')
    .replace(/\b(?:Bearer|Token|token)\s+[A-Za-z0-9._~+/=-]{6,}/gi, 'Bearer ****')
    .replace(/((?:"?(?:api[_-]?key|access[_-]?token|authorization|apikey)"?\s*[:=]\s*"?))[^"\s,}&]{4,}/gi, '$1****')
    .replace(/\bsk-[A-Za-z0-9._-]{6,}/gi, 'sk-****')
}

/**
 * Remove every configured secret from a string by literal replacement.
 *
 * Regexes alone cannot catch a key echoed verbatim inside a prose message, so
 * when we know the deployment's secrets we delete them literally. This is the
 * belt to `scrub`'s braces.
 *
 * @param {string} value
 * @param {string[]} secrets
 * @returns {string}
 */
function withoutSecrets(value, secrets) {
  let out = String(value ?? '')
  for (const secret of secrets) {
    if (typeof secret !== 'string' || secret.length < 4) continue
    out = out.split(secret).join('****')
  }
  return scrub(out)
}

/* ------------------------------------------------------------------ *
 * Request guards
 * ------------------------------------------------------------------ */

/**
 * Loopback literal check plus browser same-origin markers.
 *
 * Mirrors dsh-imagegen's `isLoopbackRequest` (which itself mirrors dsh-ssh)
 * exactly: the socket address must be a loopback literal, the Host header must
 * be a loopback host, an explicit cross-site fetch is refused, and a present
 * Origin must match the Host.
 *
 * @param {object} request
 * @returns {boolean}
 */
function isLoopbackRequest(request) {
  const address = request.socket?.remoteAddress
  if (address !== '127.0.0.1' && address !== '::1' && address !== '::ffff:127.0.0.1') return false
  const host = request.headers?.host
  if (typeof host !== 'string') return false
  let hostUrl
  try {
    hostUrl = new URL(`http://${host}`)
  } catch {
    return false
  }
  if (hostUrl.hostname !== '127.0.0.1' && hostUrl.hostname !== 'localhost' && hostUrl.hostname !== '[::1]') return false
  if (request.headers['sec-fetch-site'] === 'cross-site') return false
  const origin = request.headers.origin
  if (origin === undefined) return true
  try {
    return new URL(origin).host === hostUrl.host
  } catch {
    return false
  }
}

/** One JSON response. */
function writeJson(res, status, body) {
  const payload = JSON.stringify(body)
  res.writeHead(status, {
    'content-type': 'application/json; charset=utf-8',
    'referrer-policy': 'no-referrer',
  })
  res.end(payload)
}

/** A handled failure: always 200, always an envelope. */
function writeFail(res, code, message) {
  writeJson(res, 200, { ok: false, code, message: scrub(message) })
}

/** A handled success. */
function writeOk(res, body = {}) {
  writeJson(res, 200, { ok: true, ...body })
}

/**
 * Read a JSON request body, refusing to buffer more than `maxBytes`.
 *
 * Returns `undefined` both for "too large" and for "unparseable"; the caller
 * reports one `bad-request`, because distinguishing them to a client leaks
 * nothing useful and the cap is the security property that matters.
 *
 * @param {object} req
 * @param {number} [maxBytes]
 * @returns {Promise<object | undefined>}
 */
async function readJsonBody(req, maxBytes = MAX_JSON_BODY_BYTES) {
  const chunks = []
  let size = 0
  try {
    for await (const chunk of req) {
      const buffer = Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk)
      size += buffer.length
      if (size > maxBytes) return undefined
      chunks.push(buffer)
    }
  } catch {
    return undefined
  }
  try {
    const parsed = JSON.parse(Buffer.concat(chunks).toString('utf8'))
    return isRecord(parsed) ? parsed : undefined
  } catch {
    return undefined
  }
}

/* ------------------------------------------------------------------ *
 * Config projection (the key-hygiene boundary)
 * ------------------------------------------------------------------ */

/**
 * Collect every secret the current config holds, so responses and logs can be
 * scrubbed literally rather than heuristically.
 *
 * @param {object} config
 * @returns {string[]}
 */
function secretsOf(config) {
  const out = []
  for (const channel of config?.channels ?? []) {
    if (typeof channel?.apiKey === 'string' && channel.apiKey !== '') out.push(channel.apiKey)
  }
  for (const channel of config?.videoChannels ?? []) {
    if (typeof channel?.apiKey === 'string' && channel.apiKey !== '') out.push(channel.apiKey)
  }
  return out
}

/**
 * Project one image channel for the wire.
 *
 * EXPLICIT ALLOW-LIST, never a spread: a `...channel` here would ship `apiKey`
 * to the browser the first time somebody adds a field. Only `hasKey` reports
 * whether a secret is present.
 *
 * @param {object} channel
 * @returns {object}
 */
function projectChannel(channel) {
  return {
    id: text(channel?.id),
    name: text(channel?.name),
    apiUrl: text(channel?.apiUrl),
    protocol: text(channel?.protocol) || 'auto',
    models: Array.isArray(channel?.models)
      ? channel.models
        .filter(isRecord)
        .map(model => ({ alias: text(model.alias), id: text(model.id) }))
        .filter(model => model.alias !== '')
      : [],
    hasKey: typeof channel?.apiKey === 'string' && channel.apiKey !== '',
  }
}

/**
 * Project one video channel for the wire (same allow-list discipline).
 *
 * @param {object} channel
 * @returns {object}
 */
function projectVideoChannel(channel) {
  return {
    id: text(channel?.id),
    name: text(channel?.name),
    apiUrl: text(channel?.apiUrl),
    protocol: text(channel?.protocol) || VIDEO_PROTOCOL.promptPack,
    model: text(channel?.model),
    hasKey: typeof channel?.apiKey === 'string' && channel.apiKey !== '',
  }
}

/* ------------------------------------------------------------------ *
 * Project shaping
 * ------------------------------------------------------------------ */

/** `'shot-3'` / `'char-lin-yue'` / `'a-abc-123'` — anything path- and id-safe. */
const SAFE_REF = /^[A-Za-z0-9_-]{1,64}$/

/**
 * Resolve an asset record into the client-facing reference.
 *
 * The URL is built from ids and the stored FILE NAME only. It never embeds a
 * query parameter, an upstream URL, or anything derived from a channel, so a
 * key cannot travel inside an asset URL.
 *
 * @param {string} projectId
 * @param {object} asset
 * @returns {object}
 */
function projectAsset(projectId, asset) {
  const file = text(asset?.file)
  return {
    id: text(asset?.id),
    kind: text(asset?.kind) || ASSET_KIND.shotRef,
    ref: text(asset?.ref),
    url: file === '' ? '' : `${AIDRAMA_API.asset}/${encodeURIComponent(projectId)}/${encodeURIComponent(file)}`,
    name: text(asset?.name) || file,
    bytes: Number.isFinite(asset?.bytes) ? asset.bytes : 0,
    mime: text(asset?.mime),
    width: Number.isFinite(asset?.width) ? asset.width : undefined,
    height: Number.isFinite(asset?.height) ? asset.height : undefined,
    createdAt: Number.isFinite(asset?.createdAt) ? asset.createdAt : 0,
    origin: text(asset?.origin),
  }
}

/**
 * The per-project row the workbench project list renders.
 *
 * `listProjects()` returns cheap summaries WITHOUT `content`, but the workbench
 * needs the full stage rail. So this takes both the summary and (when the caller
 * has it) the full document, and adds `stages` from `stageView`. When no
 * document is available the stage rail is derived from the summary's counts so
 * the field is always present and always an array.
 *
 * @param {object} summary
 * @param {object | undefined} project full document, when already loaded
 * @param {(project: object) => Array<object>} stageViewFn
 * @returns {object}
 */
function projectRow(summary, project, stageViewFn) {
  const stages = project === undefined
    ? fallbackStageView(summary)
    : stageViewFn(project)
  return {
    id: text(summary?.id),
    title: text(summary?.title),
    logline: text(summary?.logline),
    aspectRatio: text(summary?.aspectRatio),
    episodes: Number.isFinite(summary?.episodes) ? summary.episodes : 1,
    shotSeconds: Number.isFinite(summary?.shotSeconds) ? summary.shotSeconds : 0,
    createdAt: Number.isFinite(summary?.createdAt) ? summary.createdAt : 0,
    updatedAt: Number.isFinite(summary?.updatedAt) ? summary.updatedAt : 0,
    stageCounts: isRecord(summary?.stageCounts) ? summary.stageCounts : {},
    stages,
    assetCount: Number.isFinite(summary?.assetCount) ? summary.assetCount : 0,
    videoTaskCount: Array.isArray(project?.videoTasks) ? project.videoTasks.length : 0,
  }
}

/**
 * Build a stage rail from a summary alone.
 *
 * Only used when a document could not be read (it vanished between the listing
 * and the read). Emitting the canonical six rows keeps the UI's rail from
 * collapsing, and `empty` is the honest status for a document we could not see.
 *
 * @param {object} summary
 * @returns {Array<object>}
 */
function fallbackStageView(summary) {
  const counts = isRecord(summary?.stageCounts) ? summary.stageCounts : {}
  return STAGES.map(stageId => {
    const meta = STAGE_META[stageId] ?? { id: stageId, label: stageId, short: stageId }
    return {
      id: stageId,
      label: meta.label,
      short: meta.short,
      status: STAGE_STATUS.empty,
      revision: 0,
      updatedAt: 0,
      note: '',
      ready: false,
      blocked: false,
      counted: Number.isFinite(counts[stageId]) ? counts[stageId] : 0,
    }
  })
}

/* ------------------------------------------------------------------ *
 * Stage helpers
 * ------------------------------------------------------------------ */

/**
 * Verify that a project document is shaped enough for the stage engine.
 *
 * `store.readProject` already repairs documents on read, so this only guards the
 * `save` action, whose body is caller-supplied.
 *
 * @param {unknown} project
 * @returns {string} `''` when acceptable, else the reason
 */
function projectShapeProblem(project) {
  if (!isRecord(project)) return 'project 必须是一个对象'
  const isIdLike = value => typeof value === 'string' && /^[A-Za-z0-9_-]{1,64}$/.test(value)
  if (!isIdLike(project.id)) return 'project.id 必须是 1-64 位的字母、数字、下划线或短横线'
  if (!isRecord(project.stages)) return 'project.stages 必须是对象'
  if (!isRecord(project.content)) return 'project.content 必须是对象'
  if (!Array.isArray(project.assets)) return 'project.assets 必须是数组'
  if (!Array.isArray(project.videoTasks)) return 'project.videoTasks 必须是数组'
  return ''
}

/**
 * Derive the visual generation targets from the bible + script.
 *
 * Called only when the model did not pass `payload.targets`, so a bare "generate
 * the visuals" still produces a sensible full batch: one model sheet per
 * character, one master plate per scene, one reference frame per shot.
 *
 * @param {object} project
 * @returns {Array<{ kind: string, ref: string, name: string }>}
 */
function deriveVisualTargets(project) {
  const targets = []
  const seen = new Set()
  const push = (kind, ref, name) => {
    if (!SAFE_REF.test(ref) || seen.has(`${kind}:${ref}`)) return
    seen.add(`${kind}:${ref}`)
    targets.push({ kind, ref, name })
  }

  const bible = isRecord(project?.content?.bible) ? project.content.bible : {}
  for (const character of Array.isArray(bible.characters) ? bible.characters : []) {
    if (!isRecord(character)) continue
    push(ASSET_KIND.characterSheet, text(character.id), text(character.name))
  }
  for (const scene of Array.isArray(bible.scenes) ? bible.scenes : []) {
    if (!isRecord(scene)) continue
    push(ASSET_KIND.sceneMaster, text(scene.id), text(scene.name))
  }

  const script = isRecord(project?.content?.script) ? project.content.script : {}
  const episodes = Array.isArray(script.episodes) ? script.episodes : []
  episodes.forEach((episode, episodeIndex) => {
    if (!isRecord(episode)) return
    const epNo = Number.isFinite(Number(episode.no)) ? Number(episode.no) : episodeIndex + 1
    const scenes = Array.isArray(episode.scenes) ? episode.scenes : []
    scenes.forEach((scene, sceneIndex) => {
      if (!isRecord(scene)) return
      const scNo = Number.isFinite(Number(scene.no)) ? Number(scene.no) : sceneIndex + 1
      const shots = Array.isArray(scene.shots) ? scene.shots : []
      shots.forEach((shot, shotIndex) => {
        if (!isRecord(shot)) return
        const no = Number.isFinite(Number(shot.no)) ? Number(shot.no) : shotIndex + 1
        push(ASSET_KIND.shotRef, text(shot.id) || `shot-${epNo}-${scNo}-${no}`, `${text(scene.slug) || '场景'} · 镜 ${no}`)
      })
    })
  })

  // Only when the script stage really was a FLAT shot list (no episode tree):
  // `content.script.shots` is otherwise a lossy one-row ghost of the wrapper,
  // and generating from it would mint assets for a shot that does not exist.
  if (seen.size === 0) {
    for (const shot of Array.isArray(script.shots) ? script.shots : []) {
      if (!isRecord(shot)) continue
      push(ASSET_KIND.shotRef, text(shot.id), text(shot.action).slice(0, 24))
    }
  }

  return targets
}

/**
 * Build the image prompt for one visual target.
 *
 * @param {object} prompts
 * @param {object} project
 * @param {{ kind: string, ref: string, name?: string }} target
 * @returns {{ prompt: string, negative: string }}
 */
function promptForTarget(prompts, project, target) {
  const style = text(project?.styleDna)
  const aspectRatio = text(project?.aspectRatio)
  const bible = isRecord(project?.content?.bible) ? project.content.bible : {}

  if (target.kind === ASSET_KIND.characterSheet) {
    const character = (Array.isArray(bible.characters) ? bible.characters : [])
      .find(item => isRecord(item) && text(item.id) === target.ref)
    const source = isRecord(character) ? character : {}
    const merged = prompts.mergeLayers({
      styleDna: style,
      // The bible's per-character prompt is a human-authored override: it wins
      // over the generic template, which is exactly what `mergeLayers` is for.
      manual: text(source.sheetPrompt),
    })
    return {
      prompt: prompts.buildCharacterSheet({
        name: text(source.name) || target.name,
        description: text(source.appearance),
        hair: text(source.hair),
        face: text(source.face),
        body: text(source.body),
        outfit: text(source.outfit),
        accessory: text(source.accessory),
        style: merged.positive || style,
        aspectRatio,
      }),
      negative: merged.negative,
    }
  }

  if (target.kind === ASSET_KIND.sceneMaster) {
    const scene = (Array.isArray(bible.scenes) ? bible.scenes : [])
      .find(item => isRecord(item) && text(item.id) === target.ref)
    const source = isRecord(scene) ? scene : {}
    const merged = prompts.mergeLayers({
      styleDna: style,
      manual: text(source.masterPrompt),
    })
    return {
      prompt: prompts.buildSceneMaster({
        name: text(source.name) || target.name,
        description: text(source.description),
        lighting: text(source.lighting),
        composition: text(source.composition),
        style: merged.positive || style,
        aspectRatio,
      }),
      negative: merged.negative,
    }
  }

  // shot-ref / first-frame: locate the shot so the frame stays on-model.
  const shot = findShot(project, target.ref)
  const cast = Array.isArray(shot?.characters) ? shot.characters : []

  // Map EVERY reference a script might use to the character's FULL card.
  //
  // This previously mapped to the name string only (`id -> name`), which meant the
  // generated prompt could say "画面中的 林晚 必须严格沿用其角色设定三视图" while
  // never describing 林晚 at all — the appearance was thrown away one step before
  // the prompt was built. A live run on the real channel produced a long-haired
  // character in a black coat for a character specified as short-haired in a navy
  // uniform. The card has to survive this lookup for the prompt to constrain
  // anything.
  const characterById = {}
  for (const character of Array.isArray(bible.characters) ? bible.characters : []) {
    if (!isRecord(character)) continue
    const id = text(character.id)
    const name = text(character.name)
    // Both the stable id and the display name resolve to the card, because a
    // script may reference either (the normalizer keeps whatever the model wrote).
    if (id !== '') characterById[id] = character
    if (name !== '') characterById[name] = character
  }
  const sceneById = {}
  for (const scene of Array.isArray(bible.scenes) ? bible.scenes : []) {
    if (!isRecord(scene)) continue
    const id = text(scene.id)
    const name = text(scene.name)
    if (id !== '') sceneById[id] = scene
    // Alias by NAME as well. A script scene's `sceneId` is derived from its own
    // slug (e.g. `scene-subway-night`) and therefore can NEVER match a bible id
    // like `scene-subway`, so an id-only lookup silently dropped the scene's
    // lighting and composition from every shot prompt. Matching on the location
    // name is the reliable bridge between the two documents.
    if (name !== '') sceneById[name] = scene
  }
  // Resolve the bible scene by id first, then by the names the shot carries.
  // The id almost never matches (see above), so the name fallbacks are what
  // actually connect a shot to its scene master's lighting and composition.
  const bibleScene = sceneById[text(shot?.sceneId)]
    ?? sceneById[text(shot?.scene)]
    ?? sceneById[text(shot?.location)]
    ?? {}

  return {
    prompt: prompts.buildShotRef({
      description: text(shot?.action) || target.name || '本镜的剧情动作与画面结果',
      shot: text(shot?.shotSize),
      camera: text(shot?.camera) || text(shot?.cameraMove),
      lighting: text(bibleScene.lighting),
      composition: text(bibleScene.composition),
      style,
      characters: cast.map(name => characterById[text(name)] ?? { name: text(name) }),
      scene: text(shot?.scene) || text(bibleScene.name),
      aspectRatio,
    }),
    negative: prompts.mergeLayers({}).negative,
  }
}

/**
 * Find one shot inside a normalized project document.
 *
 * IMPORTANT — why the nested tree is searched FIRST: `stages.normalizeShots`
 * cannot see inside `{ episodes: [...] }`. Handed a whole script payload it
 * treats the wrapper as ONE bare shot, so `content.script.shots` may contain a
 * single ghost row with empty `action` / `sceneId` whose only real content is
 * the carried-through `episodes` key. The trustworthy copy of every shot lives
 * in the episode tree, so the tree wins and the flat list is only a fallback for
 * documents whose script stage really was a flat shot list.
 *
 * @param {object} project
 * @param {string} ref
 * @returns {object | undefined}
 */
function findShot(project, ref) {
  if (ref === '') return undefined
  for (const shot of shotsFromTree(project)) {
    if (text(shot.id) === ref) return shot
  }
  const script = isRecord(project?.content?.script) ? project.content.script : {}
  for (const shot of Array.isArray(script.shots) ? script.shots : []) {
    if (isRecord(shot) && text(shot.id) === ref) return shot
  }
  return undefined
}

/**
 * Every shot nested under `script.episodes[].scenes[].shots[]`, in playback
 * order, tagged with the ids the canonical `shot-<ep>-<sc>-<no>` scheme uses.
 *
 * @param {object} project
 * @returns {Array<object>} copies carrying `id` and `seq`
 */
function shotsFromTree(project) {
  const script = isRecord(project?.content?.script) ? project.content.script : {}
  // Index the flat list by id so asset links survive the tree rebuild.
  //
  // WHY: `store.linkShotAsset` writes `imageAssetId` onto the shots it can find,
  // and the flat `content.script.shots` is where the authored ids live. But the
  // episode tree is a RAW passthrough of what the model wrote — its shots carry
  // no `id` and therefore no `imageAssetId`, and the id here is SYNTHESIZED as
  // `shot-<ep>-<sc>-<no>`. So a shot generated from the tree had an id that
  // matched the asset's ref while carrying none of the asset's link: every video
  // task came out with `firstFrame: { kind: 'image', ref: {} }` and would have
  // rendered from no first frame at all. Rebuilding the id is not enough — the
  // link has to be carried across the rebuild.
  const linkedById = new Map()
  for (const row of Array.isArray(script.shots) ? script.shots : []) {
    if (!isRecord(row)) continue
    const id = text(row.id)
    if (id === '') continue
    const assetId = text(row.imageAssetId) || text(row.firstFrameAssetId)
    if (assetId !== '') linkedById.set(id, assetId)
  }

  const out = []
  const episodes = Array.isArray(script.episodes) ? script.episodes : []
  episodes.forEach((episode, episodeIndex) => {
    if (!isRecord(episode)) return
    const epNo = Number.isFinite(Number(episode.no)) ? Number(episode.no) : episodeIndex + 1
    const scenes = Array.isArray(episode.scenes) ? episode.scenes : []
    scenes.forEach((scene, sceneIndex) => {
      if (!isRecord(scene)) return
      const scNo = Number.isFinite(Number(scene.no)) ? Number(scene.no) : sceneIndex + 1
      const shots = Array.isArray(scene.shots) ? scene.shots : []
      shots.forEach((shot, shotIndex) => {
        if (!isRecord(shot)) return
        const no = Number.isFinite(Number(shot.no)) ? Number(shot.no) : shotIndex + 1
        // CAST INHERITANCE — this is what makes the character lock reachable.
        //
        // A shot in the episode tree usually has NO `characters` field; the cast is
        // declared once on the SCENE. Because this function is what `findShot`
        // searches first, returning the bare shot meant `cast` was always empty and
        // every shot-ref prompt silently fell back to the generic
        // "与设定集保持一致" clause — so no character's appearance ever reached the
        // image model. A live run produced a long-haired, black-coated character for
        // one specified as short-haired in a navy uniform.
        //
        // A shot-level cast still wins when present, so per-shot overrides work.
        const shotCast = Array.isArray(shot.characters) && shot.characters.length > 0
          ? shot.characters
          : (Array.isArray(scene.characters) ? scene.characters : [])
        const id = text(shot.id) || `shot-${epNo}-${scNo}-${no}`
        const linked = text(shot.imageAssetId) || text(shot.firstFrameAssetId) || linkedById.get(id) || ''
        out.push({
          ...shot,
          id,
          seq: Number.isFinite(Number(shot.seq)) ? Number(shot.seq) : out.length + 1,
          sceneId: text(shot.sceneId) || text(scene.slug),
          scene: text(shot.scene) || text(scene.location),
          location: text(shot.location) || text(scene.location),
          characters: shotCast,
          // Keep the asset link attached across the rebuild; without it the video
          // stage reads an empty first frame.
          ...(linked === '' ? {} : { imageAssetId: linked, firstFrameAssetId: linked }),
        })
      })
    })
  })
  return out
}

/**
 * Every shot of a project, flattened in playback order.
 *
 * Prefers the episode tree (see `findShot` for why) and falls back to
 * `content.script.shots` only when the tree holds nothing.
 *
 * @param {object} project
 * @returns {Array<object>}
 */
function allShots(project) {
  const tree = shotsFromTree(project)
  if (tree.length > 0) return tree

  const script = isRecord(project?.content?.script) ? project.content.script : {}
  const flat = (Array.isArray(script.shots) ? script.shots : []).filter(isRecord)
  if (flat.length > 0) return flat

  return flat
}

/**
 * Pick the video channel for a request.
 *
 * Falls back to the `prompt-pack` pseudo-channel, which needs no key, no apiUrl
 * and no network — that is what lets the video stage complete for a user who has
 * configured nothing at all.
 *
 * @param {object} config
 * @param {string} [channelId]
 * @returns {object}
 */
function videoChannelFor(config, channelId) {
  const channels = Array.isArray(config?.videoChannels) ? config.videoChannels : []
  const wanted = text(channelId)
  return channels.find(channel => channel.id === wanted)
    ?? channels.find(channel => channel.id === config?.defaultVideoChannelId)
    ?? channels[0]
    ?? {
      id: 'prompt-pack',
      name: '仅提示词包（无密钥回退）',
      protocol: VIDEO_PROTOCOL.promptPack,
      apiUrl: '',
      apiKey: '',
      model: '',
    }
}

/**
 * Build one video prompt per shot for a project, without touching the network.
 *
 * Shared by the `prompt-pack` video action and the `prompt-pack` export format so
 * the two can never drift.
 *
 * @param {object} prompts
 * @param {object} project
 * @returns {{ prompts: Array<object>, note: string }}
 */
function buildPromptPack(prompts, project) {
  const shots = allShots(project)
  const rows = shots.map((shot, index) => {
    const seq = Number.isFinite(Number(shot.seq)) ? Number(shot.seq) : index + 1
    const ref = text(shot.id) || `shot-${seq}`
    const durationSec = Number.isFinite(Number(shot.durationSeconds))
      ? Number(shot.durationSeconds)
      : (Number.isFinite(Number(project?.shotSeconds)) ? Number(project.shotSeconds) : undefined)
    const authored = text(shot.videoPrompt)
    const prompt = authored !== ''
      ? authored
      : prompts.buildVideoPrompt({
        shot: text(shot.shotSize),
        camera: text(shot.cameraMove) || text(shot.camera),
        motion: text(shot.action),
        durationSec,
        dialogue: text(shot.dialogue),
        style: text(project?.styleDna),
      })
    return { ref, shot: seq, prompt }
  })

  return {
    prompts: rows,
    note: rows.length === 0
      ? '项目里还没有分镜：先完成「分场脚本」阶段再导出提示词包。'
      : `共 ${rows.length} 个镜头。把提示词与对应首帧图粘到任意视频模型即可（无需 API 密钥）。`,
  }
}

/* ------------------------------------------------------------------ *
 * Markdown export
 * ------------------------------------------------------------------ */

/** A `- 标签：值` line, or nothing when the value is empty. */
function bullet(label, value) {
  const body = text(value)
  return body === '' ? '' : `- ${label}：${body}\n`
}

/**
 * Render a project as a readable 分镜脚本.
 *
 * Structure: 项目 → 想法 → 剧情 → 逐集逐场（场次头 / 时间 / 人物 / 动作 / 对白 /
 * 镜头表 / 时长）→ 设定集 → 资产清单. Every section is skipped when empty, so a
 * half-built project still exports something readable.
 *
 * @param {object} project
 * @returns {string}
 */
function exportMarkdown(project) {
  const content = isRecord(project?.content) ? project.content : {}
  const lines = []

  lines.push(`# ${text(project?.title) || '未命名短剧'}\n`)
  if (text(project?.logline) !== '') lines.push(`> ${text(project.logline)}\n`)
  lines.push(
    `- 项目 id：${text(project?.id)}\n` +
    `- 画幅：${text(project?.aspectRatio)}\n` +
    `- 集数：${Number.isFinite(project?.episodes) ? project.episodes : 1}\n` +
    `- 单镜时长：${Number.isFinite(project?.shotSeconds) ? project.shotSeconds : 0} 秒\n` +
    `- 风格 DNA：${text(project?.styleDna)}\n`,
  )

  const idea = isRecord(content.idea) ? content.idea : undefined
  if (idea !== undefined) {
    lines.push('\n## 一、想法梳理\n')
    lines.push(bullet('题材', idea.genre))
    lines.push(bullet('基调', idea.tone))
    lines.push(bullet('主角', idea.protagonist))
    lines.push(bullet('冲突', idea.conflict))
    lines.push(bullet('钩子', idea.hook))
    lines.push(bullet('结局', idea.ending))
    if (Array.isArray(idea.questions) && idea.questions.length > 0) {
      lines.push('- 待定问题：\n')
      for (const question of idea.questions) lines.push(`  - ${text(question)}\n`)
    }
  }

  const story = isRecord(content.story) ? content.story : undefined
  if (story !== undefined) {
    lines.push('\n## 二、剧情设计\n')
    lines.push(bullet('主题', story.theme))
    if (text(story.synopsis) !== '') lines.push(`\n${text(story.synopsis)}\n`)
    for (const act of Array.isArray(story.acts) ? story.acts : []) {
      if (!isRecord(act)) continue
      lines.push(`\n### ${text(act.name) || `第 ${text(act.no)} 幕`}\n`)
      lines.push(`${text(act.summary)}\n`)
    }
  }

  const script = isRecord(content.script) ? content.script : undefined
  if (script !== undefined) {
    lines.push('\n## 三、分场脚本\n')
    const episodes = Array.isArray(script.episodes) ? script.episodes : []
    if (episodes.length === 0) {
      for (const shot of Array.isArray(script.shots) ? script.shots : []) {
        if (!isRecord(shot)) continue
        lines.push(`- 镜 ${text(shot.seq)}｜${text(shot.shotSize)}｜${text(shot.cameraMove)}｜${text(shot.action)}\n`)
      }
    }
    episodes.forEach((episode, episodeIndex) => {
      if (!isRecord(episode)) return
      const epNo = Number.isFinite(Number(episode.no)) ? Number(episode.no) : episodeIndex + 1
      lines.push(`\n### 第 ${epNo} 集：${text(episode.title)}\n`)
      if (text(episode.hook) !== '') lines.push(`> 本集钩子：${text(episode.hook)}\n`)
      const scenes = Array.isArray(episode.scenes) ? episode.scenes : []
      scenes.forEach((scene, sceneIndex) => {
        if (!isRecord(scene)) return
        const scNo = Number.isFinite(Number(scene.no)) ? Number(scene.no) : sceneIndex + 1
        const heading = text(scene.slug) || [text(scene.location), text(scene.time)].filter(Boolean).join(' · ')
        lines.push(`\n#### 第 ${epNo}-${scNo} 场　${heading}\n`)
        lines.push(bullet('地点', scene.location))
        lines.push(bullet('时间', scene.time))
        lines.push(bullet('人物', Array.isArray(scene.characters) ? scene.characters.map(text).filter(Boolean).join('、') : ''))
        lines.push(bullet('动作', scene.action))
        lines.push(bullet('时长', Number.isFinite(Number(scene.durationSec)) ? `${Number(scene.durationSec)} 秒` : ''))

        const dialogue = Array.isArray(scene.dialogue) ? scene.dialogue : []
        if (dialogue.length > 0) {
          lines.push('\n**对白**\n\n')
          for (const entry of dialogue) {
            if (isRecord(entry)) lines.push(`${text(entry.who) || '旁白'}：${text(entry.line)}\n\n`)
            else lines.push(`${text(entry)}\n\n`)
          }
        }

        const shots = Array.isArray(scene.shots) ? scene.shots : []
        if (shots.length > 0) {
          lines.push('\n| 镜号 | 景别 | 机位/运动 | 画面 | 主体动作 | 时长 |\n')
          lines.push('| --- | --- | --- | --- | --- | --- |\n')
          shots.forEach((shot, shotIndex) => {
            if (!isRecord(shot)) return
            const no = Number.isFinite(Number(shot.no)) ? Number(shot.no) : shotIndex + 1
            const duration = Number.isFinite(Number(shot.durationSec)) ? `${Number(shot.durationSec)}s` : '—'
            lines.push(
              `| ${no} | ${text(shot.shot) || '—'} | ${text(shot.camera) || '—'} | ` +
              `${text(shot.description).replace(/\|/gu, '/')} | ${text(shot.motion).replace(/\|/gu, '/')} | ${duration} |\n`,
            )
          })
        }
      })
    })
  }

  const bible = isRecord(content.bible) ? content.bible : undefined
  if (bible !== undefined) {
    lines.push('\n## 四、设定集\n')
    const characters = Array.isArray(bible.characters) ? bible.characters : []
    if (characters.length > 0) {
      lines.push('\n### 人物\n')
      for (const character of characters) {
        if (!isRecord(character)) continue
        lines.push(`\n**${text(character.name)}**（${text(character.role)}）\n\n`)
        lines.push(bullet('外观', character.appearance))
        lines.push(bullet('性格', character.personality))
        lines.push(bullet('服装', character.costume))
        lines.push(bullet('弧光', character.arc))
      }
    }
    const scenes = Array.isArray(bible.scenes) ? bible.scenes : []
    if (scenes.length > 0) {
      lines.push('\n### 场景\n')
      for (const scene of scenes) {
        if (!isRecord(scene)) continue
        lines.push(`\n**${text(scene.name)}**\n\n`)
        lines.push(bullet('地点', scene.location))
        lines.push(bullet('时间', scene.timeOfDay))
        lines.push(bullet('氛围', scene.atmosphere))
        lines.push(bullet('光线', scene.lighting))
      }
    }
  }

  const assets = Array.isArray(project?.assets) ? project.assets : []
  if (assets.length > 0) {
    lines.push('\n## 五、视觉资产\n\n')
    lines.push('| 类型 | 关联 | 文件 | 说明 |\n| --- | --- | --- | --- |\n')
    for (const asset of assets) {
      if (!isRecord(asset)) continue
      lines.push(
        `| ${text(asset.kind)} | ${text(asset.ref)} | ${text(asset.file)} | ` +
        `${text(asset.name).replace(/\|/gu, '/')} |\n`,
      )
    }
  }

  return lines.join('')
}

/**
 * Render every image + video prompt as a copy-ready list.
 *
 * Purely local: it reads the project, builds prompts through `prompts.js`, and
 * never needs a channel, a key, or a network call.
 *
 * @param {object} prompts
 * @param {object} project
 * @returns {string}
 */
function exportPromptPack(prompts, project) {
  const lines = []
  lines.push(`# ${text(project?.title) || '未命名短剧'} · 提示词包\n`)
  lines.push(`\n画幅 ${text(project?.aspectRatio)}｜单镜 ${Number.isFinite(project?.shotSeconds) ? project.shotSeconds : 0} 秒\n`)
  lines.push(`\n风格 DNA：${text(project?.styleDna)}\n`)

  const bible = isRecord(project?.content?.bible) ? project.content.bible : {}
  const children = Array.isArray(bible.characters) ? bible.characters : []
  if (children.length > 0) {
    lines.push('\n## 人物三视图\n')
    for (const character of children) {
      if (!isRecord(character)) continue
      const built = promptForTarget(prompts, project, {
        kind: ASSET_KIND.characterSheet,
        ref: text(character.id),
        name: text(character.name),
      })
      lines.push(`\n### ${text(character.name) || text(character.id)}\n\n\`\`\`\n${built.prompt}\n\`\`\`\n`)
      if (built.negative !== '') lines.push(`\n负面：${built.negative}\n`)
    }
  }

  const scenes = Array.isArray(bible.scenes) ? bible.scenes : []
  if (scenes.length > 0) {
    lines.push('\n## 场景主图\n')
    for (const scene of scenes) {
      if (!isRecord(scene)) continue
      const built = promptForTarget(prompts, project, {
        kind: ASSET_KIND.sceneMaster,
        ref: text(scene.id),
        name: text(scene.name),
      })
      lines.push(`\n### ${text(scene.name) || text(scene.id)}\n\n\`\`\`\n${built.prompt}\n\`\`\`\n`)
    }
  }

  const shots = allShots(project)
  if (shots.length > 0) {
    lines.push('\n## 分镜参考图\n')
    for (const shot of shots) {
      const ref = text(shot.id)
      const built = promptForTarget(prompts, project, { kind: ASSET_KIND.shotRef, ref, name: ref })
      lines.push(`\n### ${ref}｜${text(shot.shotSize)}\n\n\`\`\`\n${built.prompt}\n\`\`\`\n`)
    }
  }

  const pack = buildPromptPack(prompts, project)
  if (pack.prompts.length > 0) {
    lines.push('\n## 逐镜视频提示词\n')
    for (const row of pack.prompts) {
      lines.push(`\n### ${row.ref}（第 ${row.shot} 镜）\n\n\`\`\`\n${row.prompt}\n\`\`\`\n`)
    }
  }

  return lines.join('')
}

/** Strip characters no filesystem (or download dialog) enjoys. */
function safeFilename(name) {
  const cleaned = text(name).replace(/[\\/:*?"<>|\u0000-\u001f]/gu, '_').replace(/\s+/gu, ' ').trim()
  return cleaned === '' ? '未命名短剧' : cleaned.slice(0, 80)
}

/* ------------------------------------------------------------------ *
 * Factory
 * ------------------------------------------------------------------ */

/**
 * Build the route family.
 *
 * @param {{
 *   store: object,
 *   stages: object,
 *   prompts: object,
 *   video: object,
 *   resolveConfig: () => object,
 *   generateImage: (request: object) => Promise<{ images: Array<{ b64: string, mime?: string }>, model?: string, channel?: string }>,
 *   log?: (message: string) => void,
 * }} deps
 * @returns {Array<{ kind: 'exact' | 'prefix', path: string, handler: (req: object, res: object) => Promise<void> }>}
 */
export function makeAidramaRoutes(deps) {
  const { store, stages, prompts, video } = deps
  const log = typeof deps.log === 'function' ? deps.log : () => {}

  /** Resolve config defensively: a resolver failure must not 500 the surface. */
  const config = () => {
    try {
      const value = deps.resolveConfig()
      return isRecord(value) ? value : {}
    } catch (error) {
      log(`resolveConfig failed: ${messageOf(error)}`)
      return {}
    }
  }

  /** Secrets of the current config, for literal scrubbing. */
  const secrets = () => secretsOf(config())

  /** Write a fail envelope with every configured secret removed. */
  const fail = (res, code, message) => {
    writeJson(res, 200, { ok: false, code, message: withoutSecrets(message, secrets()) })
  }

  /**
   * The loopback + method guard shared by every route.
   * @returns {boolean} true when the caller may proceed
   */
  const guard = (req, res, method) => {
    if (!isLoopbackRequest(req)) {
      writeJson(res, 403, { error: 'forbidden: loopback-only' })
      return false
    }
    if (req.method !== method) {
      writeJson(res, 405, { error: `method not allowed: ${req.method}` })
      return false
    }
    return true
  }

  /* ---------------------------------------------------------------- *
   * 1. /projects — list / create / get / save / delete / advance / rerun
   * ---------------------------------------------------------------- */

  /**
   * @param {object} req
   * @param {object} res
   */
  const handleProjects = async (req, res) => {
    if (!guard(req, res, 'POST')) return
    const body = await readJsonBody(req)
    if (body === undefined) {
      fail(res, 'bad-request', `请求体必须是合法 JSON 且不超过 ${MAX_JSON_BODY_BYTES} 字节`)
      return
    }

    const action = text(body.action)
    try {
      switch (action) {
        case 'list': {
          // `listProjects()` returns cheap summaries (no `content`), but the
          // workbench rail needs the real stage view — so read each document
          // once and build BOTH the row and its stage rail from that read.
          const summaries = await store.listProjects()
          const projects = []
          for (const summary of summaries) {
            const project = await store.readProject(text(summary?.id))
            projects.push(projectRow(summary, project, current => stages.stageView(current)))
          }
          writeJson(res, 200, { ok: true, projects })
          return
        }

        case 'create': {
          const project = stages.newProjectFrom({
            title: text(body.title),
            logline: text(body.logline),
            aspectRatio: text(body.aspectRatio),
            episodes: Number.isFinite(Number(body.episodes)) ? Number(body.episodes) : undefined,
            shotSeconds: Number.isFinite(Number(body.shotSeconds)) ? Number(body.shotSeconds) : undefined,
            styleDna: text(body.styleDna),
          })
          const value = config()
          if (text(project.styleDna) === '' && text(value.styleDna) !== '') project.styleDna = text(value.styleDna)
          if (text(project.aspectRatio) === '' && text(value.aspectRatio) !== '') project.aspectRatio = text(value.aspectRatio)
          await store.writeProject(project)
          writeJson(res, 200, { ok: true, project })
          return
        }

        case 'get': {
          const project = await store.readProject(text(body.id))
          if (project === undefined) {
            fail(res, 'not-found', `项目不存在：${text(body.id)}`)
            return
          }
          const view = stages.stageView(project)
          const assets = project.assets.map(asset => projectAsset(project.id, asset))
          const videoTasks = Array.isArray(project.videoTasks) ? project.videoTasks : []
          const taskIds = new Set(videoTasks.map(task => text(task?.assetId)).filter(Boolean))
          writeJson(res, 200, {
            ok: true,
            project,
            stages: view,
            assets,
            // Counts the workbench header shows; kept here so a single `get`
            // paints the whole workbench without a second round trip.
            videoTaskCount: videoTasks.length,
            persistedVideoAssets: assets.filter(asset => taskIds.has(asset.id)).length,
          })
          return
        }

        case 'save': {
          const project = body.project
          const problem = projectShapeProblem(project)
          if (problem !== '') {
            fail(res, 'bad-request', problem)
            return
          }
          const existing = await store.readProject(project.id)
          if (existing === undefined) {
            fail(res, 'not-found', `项目不存在：${project.id}，请先 create`)
            return
          }
          // Optimistic concurrency: a client that edited a document somebody
          // else has since saved must not silently clobber it.
          const expected = body.revision ?? body.updatedAt
          if (expected !== undefined && Number.isFinite(Number(expected)) && Number(existing.updatedAt) !== Number(expected)) {
            writeJson(res, 200, {
              ok: false,
              code: 'conflict',
              message: '该项目已被其他地方修改，请重新载入后再保存',
              current: existing.updatedAt,
              expected: Number(expected),
            })
            return
          }
          // `writeProject` mutates the object it is handed (it stamps updatedAt),
          // so it must receive a copy the caller does not also own.
          const saved = await store.writeProject({ ...project, schemaVersion: Number.isFinite(project.schemaVersion) ? project.schemaVersion : PROJECT_SCHEMA_VERSION })
          writeJson(res, 200, { ok: true, project: saved })
          return
        }

        case 'delete': {
          const removed = await store.deleteProject(text(body.id))
          if (!removed) {
            fail(res, 'not-found', `项目不存在：${text(body.id)}`)
            return
          }
          writeJson(res, 200, { ok: true })
          return
        }

        case 'advance': {
          const project = await store.readProject(text(body.id))
          if (project === undefined) {
            fail(res, 'not-found', `项目不存在：${text(body.id)}`)
            return
          }
          const stageId = text(body.stage)
          const verdict = stages.advanceGuard(project, stageId)
          if (!verdict.ok) {
            fail(res, 'stage-blocked', verdict.reason)
            return
          }
          // Advancing means "the content is current now": a stage that was only
          // stale because an upstream changed is promoted back to ready.
          const entry = project.stages[stageId]
          if (entry !== null && typeof entry === 'object') {
            entry.status = STAGE_STATUS.ready
            entry.updatedAt = Date.now()
          }
          await store.writeProject(project)
          writeJson(res, 200, {
            ok: true,
            project,
            ...(typeof verdict.warning === 'string' && verdict.warning !== '' ? { warning: verdict.warning } : {}),
          })
          return
        }

        case 'rerun': {
          const project = await store.readProject(text(body.id))
          if (project === undefined) {
            fail(res, 'not-found', `项目不存在：${text(body.id)}`)
            return
          }
          const stageId = text(body.stage)
          if (!isStageId(stageId)) {
            fail(res, 'bad-request', `未知阶段：${stageId}`)
            return
          }
          // Re-running an earlier stage keeps every later artifact but flags the
          // dependents stale. `markStageReady` deliberately does NOT do this.
          stages.markStageStale(project, stageId, text(body.reason) || '已标记需要重做')
          stages.invalidateAfter(project, stageId)
          await store.writeProject(project)
          writeJson(res, 200, { ok: true, project })
          return
        }

        default: {
          fail(res, 'bad-request', `未知 action：${action === '' ? '(空)' : action}`)
        }
      }
    } catch (error) {
      // A `TypeError` here is almost always a bad id reaching the store.
      fail(res, error instanceof TypeError ? 'bad-request' : 'projects-failed', messageOf(error))
    }
  }

  /* ---------------------------------------------------------------- *
   * 2. /stage — brief / commit / generate / clear
   * ---------------------------------------------------------------- */

  /**
   * Commit a text stage: normalize through stages.js, then mark ready.
   * @returns {Promise<object>}
   */
  const commitStage = async (project, stageId, payload, note) => {
    if (!TEXT_STAGES.includes(stageId)) {
      throw new TypeError(`阶段「${stageId}」不是文本阶段，不能用 commit 提交`)
    }
    stages.markStageReady(project, stageId, payload, note, { origin: ORIGIN.agent })
    return project
  }

  /**
   * Generate the visual assets for a batch of targets.
   *
   * ONE FAILED TARGET NEVER ABORTS THE BATCH: each target is wrapped, a failure
   * lands in `failures`, and the loop continues. That is the difference between
   * "3 of 12 frames failed" and "the whole generation was lost".
   *
   * @returns {Promise<{ assets: Array<object>, failures: Array<object> }>}
   */
  const generateVisual = async (project, targets, note) => {
    const value = config()
    const assets = []
    const failures = []

    // Mark the stage ready BEFORE storing any bytes.
    //
    // This ordering is load-bearing. `store.putAsset` reads the document, pushes
    // the asset and writes it back — so it composes correctly with ITSELF, but
    // NOT with a whole-document write from a stale in-memory copy. Writing
    // `project` after the batch would silently erase every asset the batch just
    // stored (a lost update). So the stage is recorded first, and `putAsset` is
    // the only writer afterwards.
    stages.markStageReady(
      project,
      'visual',
      { ...(isRecord(project.content.visual) ? project.content.visual : {}), generatedAt: Date.now() },
      note,
      { origin: ORIGIN.imageModel },
    )
    await store.writeProject(project)

    for (const target of targets) {
      const kind = text(target?.kind) || ASSET_KIND.shotRef
      const ref = text(target?.ref)
      try {
        if (ref === '') throw new TypeError('target.ref 不能为空')
        if (!SAFE_REF.test(ref)) throw new TypeError(`target.ref 不合法：${ref}`)

        const built = promptForTarget(prompts, project, { kind, ref, name: text(target?.name) })
        const result = await deps.generateImage({
          prompt: built.prompt,
          negative: built.negative,
          aspectRatio: text(project?.aspectRatio) || text(value.aspectRatio),
          styleDna: text(project?.styleDna) || text(value.styleDna),
          model: text(target?.model),
          // The target's identity travels with the request so a caller (and the
          // host entry's logging) can attribute a failure to the exact asset.
          kind,
          ref,
        })
        const first = Array.isArray(result?.images) ? result.images[0] : undefined
        const b64 = text(first?.b64)
        if (b64 === '') throw new Error('图像模型没有返回图片数据')

        // The stored extension must match the real bytes.
        //
        // This was hard-coded `.png` while `mime` came from the sniffed
        // payload, so a JPEG response was stored as `mime: image/jpeg` under a
        // `.png` name. The asset route rebuilds its Content-Type from the URL
        // extension, so the correct MIME never reached the browser and the file
        // was served as image/png — bytes that no strict viewer will render.
        // d1api.xin returns JPEG for roughly a quarter of images, so this was
        // not a corner case.
        const mime = text(first?.mime) || 'image/png'
        const record = await store.putAsset(project.id, {
          kind,
          ref,
          name: `${text(target?.name) || ref}${extensionForMime(mime)}`,
          bytes: b64,
          mime,
          ext: extensionForMime(mime),
          origin: ORIGIN.imageModel,
          meta: {
            prompt: built.prompt,
            negative: built.negative,
            model: text(result?.model),
            channel: text(result?.channel),
          },
        })
        assets.push(projectAsset(project.id, record))

        // Link the still back onto its shot. Without this the video stage reads
        // an empty first frame — see store.linkShotAsset.
        try {
          await store.linkShotAsset(project.id, ref, record.id, kind)
        } catch (error) {
          // A failed link must not lose the image the user already paid for.
          log(`linkShotAsset(${ref}) failed: ${messageOf(error)}`)
        }
      } catch (error) {
        failures.push({ kind, ref, message: withoutSecrets(messageOf(error), secrets()) })
      }
    }

    return { assets, failures }
  }

  const handleStage = async (req, res) => {
    if (!guard(req, res, 'POST')) return
    const body = await readJsonBody(req)
    if (body === undefined) {
      fail(res, 'bad-request', `请求体必须是合法 JSON 且不超过 ${MAX_JSON_BODY_BYTES} 字节`)
      return
    }

    const stageId = text(body.stage)
    const action = text(body.action)
    const payload = body.payload
    const note = text(body.note)

    try {
      // `brief` is answered without a project: the model reads the contract
      // BEFORE it has written anything, and a brief must never depend on state.
      if (action === 'brief') {
        if (TEXT_STAGES.includes(stageId)) {
          const brief = prompts.TEXT_STAGE_BRIEF[stageId]
          if (brief === undefined) {
            fail(res, 'bad-request', `阶段「${stageId}」没有任务说明`)
            return
          }
          writeJson(res, 200, { ok: true, brief })
          return
        }
        // A non-text stage has no JSON contract (visual is produced by an image
        // model, video by a video model). Handing back the template catalog is
        // far more useful than an error, and it is what the workbench lists.
        writeJson(res, 200, {
          ok: true,
          brief: {
            stage: stageId,
            text: false,
            note: TEXT_STAGES.includes(stageId)
              ? ''
              : `「${STAGE_META[stageId]?.label ?? stageId}」不是文本阶段：它由图像/视频模型产出，不由会话模型撰写。`,
            templates: prompts.TEMPLATE_CATALOG,
          },
        })
        return
      }

      const project = await store.readProject(text(body.projectId))
      if (project === undefined) {
        fail(res, 'not-found', `项目不存在：${text(body.projectId)}`)
        return
      }

      switch (action) {
        case 'commit': {
          await commitStage(project, stageId, payload, note)
          await store.writeProject(project)
          writeJson(res, 200, { ok: true, project })
          return
        }

        case 'generate': {
          if (!IMAGE_STAGES.includes(stageId)) {
            fail(res, 'bad-request', `阶段「${stageId}」不产生图像资产（只支持 ${IMAGE_STAGES.join(', ')}）`)
            return
          }
          const requested = Array.isArray(payload?.targets) ? payload.targets.filter(isRecord) : []
          const targets = requested.length > 0 ? requested : deriveVisualTargets(project)
          if (targets.length === 0) {
            fail(res, 'no-targets', '没有可生成的目标：请先完成「设定集」与「分场脚本」阶段，或在 payload.targets 里指定')
            return
          }
          const result = await generateVisual(project, targets, note)
          writeJson(res, 200, { ok: true, assets: result.assets, failures: result.failures })
          return
        }

        case 'clear': {
          if (!isStageId(stageId)) {
            fail(res, 'bad-request', `未知阶段：${stageId}`)
            return
          }
          const entry = project.stages[stageId]
          if (entry !== null && typeof entry === 'object') {
            entry.status = STAGE_STATUS.empty
            entry.note = ''
            entry.updatedAt = Date.now()
          }
          project.content[stageId] = null
          // Clearing an input invalidates everything built from it.
          stages.invalidateAfter(project, stageId)
          await store.writeProject(project)
          writeJson(res, 200, { ok: true, project })
          return
        }

        default: {
          fail(res, 'bad-request', `未知 action：${action === '' ? '(空)' : action}`)
        }
      }
    } catch (error) {
      fail(res, error instanceof TypeError ? 'bad-request' : 'stage-failed', messageOf(error))
    }
  }

  /* ---------------------------------------------------------------- *
   * 3. /video — submit / status / cancel / prompt-pack
   * ---------------------------------------------------------------- */

  const handleVideo = async (req, res) => {
    if (!guard(req, res, 'POST')) return
    const body = await readJsonBody(req)
    if (body === undefined) {
      fail(res, 'bad-request', `请求体必须是合法 JSON 且不超过 ${MAX_JSON_BODY_BYTES} 字节`)
      return
    }

    const action = text(body.action)
    const value = config()

    try {
      const project = await store.readProject(text(body.projectId))
      if (project === undefined) {
        fail(res, 'not-found', `项目不存在：${text(body.projectId)}`)
        return
      }

      switch (action) {
        case 'prompt-pack': {
          // Deliberately BEFORE any channel resolution: the pack is local, so it
          // must work with no video channel, no key and no network.
          const pack = buildPromptPack(prompts, project)
          writeJson(res, 200, { ok: true, pack })
          return
        }

        case 'submit': {
          const requested = Array.isArray(body.shotRefs) ? body.shotRefs.map(text).filter(Boolean) : []
          const shots = allShots(project)
          const wanted = requested.length > 0
            ? shots.filter(shot => requested.includes(text(shot.id)))
            : shots
          if (wanted.length === 0) {
            fail(res, 'no-targets', '没有可提交的镜头：请先完成「分场脚本」阶段，或在 shotRefs 里指定镜头')
            return
          }

          const channel = videoChannelFor(value, body.channelId)
          const tasks = []
          const failures = []
          for (const shot of wanted) {
            const ref = text(shot.id)
            try {
              const durationSec = Number.isFinite(Number(shot.durationSeconds))
                ? Number(shot.durationSeconds)
                : Number(project.shotSeconds)
              const submitted = await video.submitVideo({
                channel,
                prompt: text(shot.videoPrompt) !== ''
                  ? text(shot.videoPrompt)
                  : prompts.buildVideoPrompt({
                    shot: text(shot.shotSize),
                    camera: text(shot.cameraMove) || text(shot.camera),
                    motion: text(shot.action),
                    durationSec,
                    dialogue: text(shot.dialogue),
                    style: text(project.styleDna),
                  }),
                firstFrame: firstFrameDataUrl(project, shot),
                durationSec,
                aspectRatio: text(project.aspectRatio),
              })
              const task = {
                id: `vt-${shot.id ?? Date.now()}`,
                shotRef: ref,
                taskId: text(submitted?.taskId),
                status: text(submitted?.status) || 'queued',
                channelId: text(channel.id),
                protocol: text(channel.protocol),
                prompt: '',
                createdAt: Date.now(),
                updatedAt: Date.now(),
                raw: submitted?.raw ?? {},
              }
              tasks.push(task)
            } catch (error) {
              failures.push({ ref, message: withoutSecrets(messageOf(error), secrets()) })
            }
          }

          if (tasks.length > 0) {
            const existing = Array.isArray(project.videoTasks) ? project.videoTasks : []
            project.videoTasks = [...existing, ...tasks]
            stages.markStageReady(
              project,
              'video',
              { ...(isRecord(project.content.video) ? project.content.video : {}), submittedAt: Date.now(), tasks: project.videoTasks },
              '',
              { origin: ORIGIN.videoModel },
            )
            await store.writeProject(project)
          }
          writeJson(res, 200, { ok: true, tasks, failures })
          return
        }

        case 'status': {
          const taskId = text(body.taskId)
          const existing = (Array.isArray(project.videoTasks) ? project.videoTasks : [])
            .find(task => isRecord(task) && (text(task.taskId) === taskId || text(task.id) === taskId))
          if (existing === undefined) {
            fail(res, 'not-found', `视频任务不存在：${taskId}`)
            return
          }
          const channel = videoChannelFor(value, existing.channelId ?? body.channelId)
          const polled = await video.pollVideo({ channel, taskId: text(existing.taskId) })

          existing.status = text(polled?.status) || existing.status
          existing.updatedAt = Date.now()
          // The sibling module OMITS absent optional keys rather than nulling
          // them, so only assign what actually came back.
          if (polled?.videoUrl !== undefined) existing.videoUrl = polled.videoUrl
          if (polled?.coverUrl !== undefined) existing.coverUrl = polled.coverUrl
          if (polled?.error !== undefined) existing.error = withoutSecrets(polled.error, secrets())
          if (polled?.raw !== undefined) existing.raw = polled.raw

          // Persist only a TERMINAL state: an in-flight poll must not rewrite the
          // document on every tick (and a transient read must not "un-finish" a
          // task that already succeeded).
          if (VIDEO_TASK_TERMINAL.has(existing.status)) {
            await store.writeProject(project)
          }
          writeJson(res, 200, { ok: true, task: existing, terminal: VIDEO_TASK_TERMINAL.has(existing.status) })
          return
        }

        case 'cancel': {
          // Best effort by design: none of the supported protocols expose a
          // reliable cancel endpoint, so we release our own bookkeeping and
          // report success rather than pretending we stopped an upstream job.
          const taskId = text(body.taskId)
          const existing = (Array.isArray(project.videoTasks) ? project.videoTasks : [])
            .find(task => isRecord(task) && (text(task.taskId) === taskId || text(task.id) === taskId))
          if (existing !== undefined) {
            existing.status = 'failed'
            existing.error = '已在本机取消（上游任务可能仍在计费）'
            existing.updatedAt = Date.now()
            await store.writeProject(project)
          }
          writeJson(res, 200, { ok: true })
          return
        }

        default: {
          fail(res, 'bad-request', `未知 action：${action === '' ? '(空)' : action}`)
        }
      }
    } catch (error) {
      fail(res, error instanceof TypeError ? 'bad-request' : 'video-failed', messageOf(error))
    }
  }

  /* ---------------------------------------------------------------- *
   * 4. /asset (prefix) — stream stored bytes
   * ---------------------------------------------------------------- */

  /**
   * Parse `/api/dsh-aidrama/asset/<projectId>/<file>`.
   *
   * Both segments are matched against the store's own validators rather than
   * merely decoded, so `..`, an absolute path or a drive-relative name can never
   * reach the filesystem.
   *
   * @param {string} url
   * @returns {{ projectId: string, file: string } | undefined}
   */
  const assetRefFrom = (url) => {
    const path = String(url ?? '').split('?')[0].split('#')[0]
    if (!path.startsWith(`${AIDRAMA_API.asset}/`)) return undefined
    const rest = path.slice(AIDRAMA_API.asset.length + 1)
    const slash = rest.indexOf('/')
    if (slash <= 0) return undefined
    let projectId
    let file
    try {
      projectId = decodeURIComponent(rest.slice(0, slash))
      file = decodeURIComponent(rest.slice(slash + 1))
    } catch {
      return undefined
    }
    if (!store.isProjectId(projectId) || !store.isSafeFile(file)) return undefined
    return { projectId, file }
  }

  const handleAsset = async (req, res) => {
    if (!isLoopbackRequest(req)) {
      writeJson(res, 403, { error: 'forbidden: loopback-only' })
      return
    }
    if (req.method !== 'GET' && req.method !== 'HEAD') {
      writeJson(res, 405, { error: `method not allowed: ${req.method}` })
      return
    }

    const ref = assetRefFrom(req.url)
    if (ref === undefined) {
      writeJson(res, 404, { error: 'asset not found' })
      return
    }

    let stored
    try {
      stored = await store.readAsset(ref.projectId, ref.file)
    } catch {
      stored = undefined
    }
    if (stored === undefined) {
      writeJson(res, 404, { error: 'asset not found' })
      return
    }

    // Anything that is not a known media type is forced to a download so the
    // browser can never render it on the loopback origin.
    const declared = text(stored.mime).split(';')[0].trim().toLowerCase()
    const guessed = MIME_BY_EXT[ref.file.slice(ref.file.lastIndexOf('.')).toLowerCase()]
    const resolved = SAFE_INLINE_MIME[declared] ?? SAFE_INLINE_MIME[guessed] ?? 'application/octet-stream'
    const inline = SAFE_INLINE_MIME[resolved] !== undefined

    const data = Buffer.isBuffer(stored.data) ? stored.data : Buffer.from(stored.data ?? [])
    res.writeHead(200, {
      'content-type': inline ? resolved : 'application/octet-stream',
      'content-length': data.byteLength,
      'cache-control': 'private, max-age=3600',
      'referrer-policy': 'no-referrer',
      'x-content-type-options': 'nosniff',
      ...(inline ? {} : { 'content-disposition': `attachment; filename="${encodeURIComponent(ref.file)}"` }),
    })
    if (req.method === 'HEAD') {
      res.end()
      return
    }
    res.end(data)
  }

  /* ---------------------------------------------------------------- *
   * 5. /export — json / markdown / prompt-pack
   * ---------------------------------------------------------------- */

  const handleExport = async (req, res) => {
    if (!guard(req, res, 'POST')) return
    const body = await readJsonBody(req)
    if (body === undefined) {
      fail(res, 'bad-request', `请求体必须是合法 JSON 且不超过 ${MAX_JSON_BODY_BYTES} 字节`)
      return
    }

    try {
      const project = await store.readProject(text(body.projectId))
      if (project === undefined) {
        fail(res, 'not-found', `项目不存在：${text(body.projectId)}`)
        return
      }

      const base = safeFilename(project.title)
      const format = text(body.format) || 'json'
      switch (format) {
        case 'json': {
          writeJson(res, 200, {
            ok: true,
            filename: `${base}.json`,
            content: `${JSON.stringify(project, null, 2)}\n`,
          })
          return
        }
        case 'markdown':
        case 'md': {
          writeJson(res, 200, { ok: true, filename: `${base}-分镜脚本.md`, content: exportMarkdown(project) })
          return
        }
        case 'prompt-pack': {
          writeJson(res, 200, { ok: true, filename: `${base}-提示词包.md`, content: exportPromptPack(prompts, project) })
          return
        }
        default: {
          fail(res, 'bad-request', `未知导出格式：${format}（支持 json / markdown / prompt-pack）`)
        }
      }
    } catch (error) {
      fail(res, 'export-failed', messageOf(error))
    }
  }

  /* ---------------------------------------------------------------- *
   * 6. /config — the key-hygiene boundary
   * ---------------------------------------------------------------- */

  const handleConfig = async (req, res) => {
    if (!guard(req, res, 'POST')) return
    const body = await readJsonBody(req, MAX_JSON_BODY_BYTES)
    if (body === undefined) {
      fail(res, 'bad-request', `请求体必须是合法 JSON 且不超过 ${MAX_JSON_BODY_BYTES} 字节`)
      return
    }

    try {
      const value = config()
      // EXPLICIT PROJECTION. Never spread `value` or a channel here: this is the
      // one route whose entire purpose is to prove no key crosses the wire.
      writeJson(res, 200, {
        ok: true,
        config: {
          enabled: value.enabled !== false,
          announceToAgent: value.announceToAgent !== false,
          allowAgentGeneration: value.allowAgentGeneration !== false,
          aspectRatio: text(value.aspectRatio),
          shotSeconds: Number.isFinite(value.shotSeconds) ? value.shotSeconds : 0,
          styleDna: text(value.styleDna),
          channels: (Array.isArray(value.channels) ? value.channels : []).map(projectChannel),
          defaultChannelId: text(value.defaultChannelId),
          defaultModel: text(value.defaultModel),
          videoChannels: (Array.isArray(value.videoChannels) ? value.videoChannels : []).map(projectVideoChannel),
          defaultVideoChannelId: text(value.defaultVideoChannelId),
          stages: STAGES.map(stageId => ({
            id: stageId,
            label: STAGE_META[stageId].label,
            short: STAGE_META[stageId].short,
          })),
        },
      })
    } catch (error) {
      fail(res, 'config-failed', messageOf(error))
    }
  }

  return [
    { kind: 'exact', path: AIDRAMA_API.projects, handler: handleProjects },
    { kind: 'exact', path: AIDRAMA_API.stage, handler: handleStage },
    { kind: 'exact', path: AIDRAMA_API.video, handler: handleVideo },
    { kind: 'prefix', path: AIDRAMA_API.asset, handler: handleAsset },
    { kind: 'exact', path: AIDRAMA_API.export, handler: handleExport },
    { kind: 'exact', path: AIDRAMA_API.config, handler: handleConfig },
  ]
}

/**
 * Resolve a shot's first frame into a data URL for a video request.
 *
 * Reads the stored bytes and inlines them, because every supported protocol
 * either wants a public URL (which we cannot mint) or accepts a data URL. The
 * URL itself carries no credential — only the loopback asset path does.
 *
 * @param {object} project
 * @param {object} shot
 * @returns {Promise<string | undefined>}
 */
async function firstFrameDataUrl(project, shot) {
  const assetId = text(shot?.firstFrameAssetId) || text(shot?.imageAssetId)
  if (assetId === '') return undefined
  const asset = (Array.isArray(project?.assets) ? project.assets : [])
    .find(item => isRecord(item) && text(item.id) === assetId)
  if (asset === undefined) return undefined
  const file = text(asset.file)
  if (file === '') return undefined
  return `${AIDRAMA_API.asset}/${encodeURIComponent(text(project.id))}/${encodeURIComponent(file)}`
}
